{
 "title": "smart farm",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Silo locations",
   "type": "geomap",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"farm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"loc_silo1\" or r[\"_measurement\"] == \"loc_silo2\")\n  |> filter(fn: (r) =>r._field == \"longitude\" or r._field == \"latitude\")  \n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> group()  \n  |> drop(columns: [\"_start\", \"_stop\", \"_time\",\"_measurement\",\"_value\"])\n"
    }
   ]
  },
  {
   "title": "Silo weights",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"farm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weight_silo1\" or r[\"_measurement\"] == \"weight_silo2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"weight\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "capacity level of silo 2",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"farm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp_Humidity_silo2\" or r[\"_measurement\"] == \"weight_silo2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\" or r[\"_field\"] == \"temperature\" or r[\"_field\"] == \"weight\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "capacity level of silo 1",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"farm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp_Humidity_silo1\" or r[\"_measurement\"] == \"weight_silo1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\" or r[\"_field\"] == \"temperature\" or r[\"_field\"] == \"weight\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "silos humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"farm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp_Humidity_silo1\" or r[\"_measurement\"] == \"temp_Humidity_silo2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "silos temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"farm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"temp_Humidity_silo1\" or r[\"_measurement\"] == \"temp_Humidity_silo2\")\n  |> filter(fn: (r) =>r[\"_field\"] == \"temperature\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "silos weights evolution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "masst" } },
   "targets": [
    {
     "query": "from(bucket: \"farm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"weight_silo1\" or r[\"_measurement\"] == \"weight_silo2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"weight\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Log Events ",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nimport \"sampledata\"\n\nfrom(bucket: \"farm\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"event\")\n  |> filter(fn: (r) => r[\"_field\"] == \"silo\" or r[\"_field\"] == \"metric\" or r[\"_field\"] == \"severity\")\n  |> keep(columns: [\"_time\",\"_value\", \"_field\"])\n  |> schema.fieldsAsCols()\n"
    }
   ]
  }
 ]
}