{
 "title": "machines monitoring",
 "time": { "from": "2023-01-22T18:54:01.192Z", "to": "2023-01-22T23:02:19.386Z" },
 "templating": {
  "list": [
   {
    "name": "products",
    "label": "products",
    "query": "import \"influxdata/influxdb/schema\"\nimport \"sampledata\"\n\nfrom(bucket: \"exam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machines\")\n  |> filter(fn: (r) => r[\"_field\"] == \"product\")\n  |> keep(columns: [\"_value\"])"
   },
   {
    "name": "machine",
    "label": "machine",
    "query": "import \"influxdata/influxdb/schema\"\nimport \"sampledata\"\n\nfrom(bucket: \"exam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machines\")\n  |> filter(fn: (r) => r[\"_field\"] == \"product\")\n  |> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  { "title": "Machines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$products",
   "type": "canvas",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "repeat": "products",
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nimport \"sampledata\"\n\nfrom(bucket: \"exam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machines\")\n  |> filter(fn: (r) => r[\"_field\"] == \"product\" or r[\"_field\"] == \"target\" or r[\"_field\"] == \"prediction\")\n  |> schema.fieldsAsCols()  \n  |> filter(fn: (r) => r.product == \"${products}\")\n  |> keep(columns: [\"prediction\",\"target\"])\n  |> yield()\n"
    }
   ]
  },
  { "title": "Machine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "metrics of the machine $machine",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nimport \"sampledata\"\n\nfrom(bucket: \"exam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machines\")\n  |> filter(fn: (r) => r[\"_field\"] == \"product\" or r[\"_field\"] == \"air_temp\" or r[\"_field\"] == \"process_temp\" or r[\"_field\"] == \"torque\")\n  |> schema.fieldsAsCols()  \n  |> filter(fn: (r) => r.product == \"${machine}\")\n  |> keep(columns: [\"air_temp\",\"process_temp\",\"torque\"])\n  |> yield()"
    }
   ]
  },
  {
   "title": "$machine",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nimport \"sampledata\"\n\nfrom(bucket: \"exam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machines\")\n  |> filter(fn: (r) => r[\"_field\"] == \"product\" or r[\"_field\"] == \"rotation_speed\")\n  |> schema.fieldsAsCols()  \n  |> filter(fn: (r) => r.product == \"${machine}\")\n  |> keep(columns: [\"rotation_speed\"])\n  |> yield()"
    }
   ]
  },
  {
   "title": "tool wear $machine",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nimport \"sampledata\"\n\nfrom(bucket: \"exam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machines\")\n  |> filter(fn: (r) => r[\"_field\"] == \"product\" or r[\"_field\"] == \"tool_wear\")\n  |> schema.fieldsAsCols()  \n  |> filter(fn: (r) => r.product == \"${machine}\")\n  |> keep(columns: [\"tool_wear\"])\n  |> yield()"
    }
   ]
  },
  {
   "title": "temperature of machine $machine",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/schema\"\nimport \"sampledata\"\n\nfrom(bucket: \"exam\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"machines\")\n  |> filter(fn: (r) => r[\"_field\"] == \"product\" or r[\"_field\"] == \"process_temp\" or r[\"_field\"] == \"air_temp\")\n  |> schema.fieldsAsCols()  \n  |> filter(fn: (r) => r.product == \"${machine}\")\n  |> keep(columns: [\"process_temp\",\"air_temp\",\"_time\"])"
    }
   ]
  }
 ]
}